spring:
  main:
    banner-mode: off
  application:
    name: github-action-research
server:
  node: node0
  servlet:
    context-path: /${spring.application.name}
  port: 8080
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: ALWAYS