# 定义构建流程
name: Build Process

on:
  push:
    branches:
      - master
    tags:
      - 'release-v*'

jobs:
  # 定义构建作业
  build:
    # 在 Ubuntu 环境中运行
    runs-on: ubuntu-latest
    
    steps:
      # 步骤：检出代码
      - name: Checkout code
        uses: actions/checkout@v3
      
      # 步骤：设置 Java 环境为 JDK 17，并使用 temurin 发行版，缓存 Maven
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      
      # 步骤：构建 Maven 项目
      - name: Build Maven Project
        run: |
          # 运行打包 Maven 项目的命令
          mvn -DskipTests package
