name: ssh

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 连接服务器(SSH)
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ls -a
          host: ${{ secrets.TENCENT_3_YEARS_SSH_HOST }}
          username: root
          port: 22
          privateKey: ${{ secrets.TENCENT_3_YEARS_SSH_PRIVATE_KEY}}
