name: ssh

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 连接服务器(SSH)
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.TENCENT_3_YEARS_SSH_HOST }}
          username: root
          port: 22
          privateKey: ${{ secrets.TENCENT_3_YEARS_SSH_PRIVATE_KEY}}
          command: |
            cd /server
            echo 'IMAGE_VERSION=1.2.1' > docker-compose-services.env
            docker compose --env-file docker-compose-services.env  -f docker-compose-services.yml up -d --force-recreate --scale github-action-research=3
            docker image prune -a --force --filter "until=24h"
